---
projects:
  proj12:
    root: csd3
    mode: "ug=rwx,+t"
    users:
      proj12:       # owner
        guid: 1100
        groups: []
      proj12-member:
        guid: 1101
        groups: []
  proj3:
    root: srcp
    mode: "ug=rwx,+t"
    users:
      proj3:
        guid: 3100
        groups: []
      proj3-member:
        guid: 3101
        groups: []
    
  
lustre: # can mostly be overriden on a per-client basis
  release: "2.12.4"
  fs_name: test_fs1
  key_duration: 525600 # duration (s) of lustre key validity
  mgs_addr: "{{ hostvars[groups['lustre_server'][0]]['ansible_host'] }}"
  mgs_lnet: "{{ hostvars[groups['lustre_server'][0]]['lnet_eth0_net_type'] }}"
  squash_gid: 99
  squash_uid: 99
  trusted: False
  admin: False
  deny_unknown: False
  fileset: '' # Use /DIRNAME to mount to a specific subdir and restrict client to that
  mount_point: /mnt/lustre/
  ssk_flavor: 'null' # e.g. skn or 'null' (not null, that's different!) to disable TODO: This can't be changed per-client, so where does it belong?
  idmap: []
users:
  root:
    guid: 0
    groups: []
  nobody:
    guid: 99
    groups: []
