---
lustre_release: "2.12.2"

fs_name: test_fs1
lnet_suffix: "{{ hostvars[groups['lustre_server'][0]]['lnet_eth0_net_type'] }}"
mgsnode: "{{ hostvars[groups['lustre_server'][0]]['ansible_host'] }}"
projects: # key defines project directory, value defines uid/gid for owner (should start at 1100) and start of project user uid/gid range
  proj12: 1100
  proj3: 3100