---
lustre_release: "2.12.2"

fs_name: test_fs1
key_duration: 525600 # duration (s) lustre keys valid for
lnet_suffix: "{{ hostvars[groups['lustre_server'][0]]['lnet_eth0_net_type'] }}"
mgsnode: "{{ hostvars[groups['lustre_server'][0]]['ansible_host'] }}"
projects:
  proj12:
    base: 1100 # uid/gid for owner (should start at 1100) and start of shared project user uid/gid range
  proj3:
    base: 3100
