---
projects:
  proj12:
    base: 1100 # uid/gid for owner (should start at 1100) and start of shared project user uid/gid range
  proj3:
    base: 3100
lustre:
  release: "2.12.2"
  fs_name: test_fs1
  key_duration: 525600 # duration (s) lustre keys valid for
  mgs_addr: "{{ hostvars[groups['lustre_server'][0]]['ansible_host'] }}"
  mgs_lnet: "{{ hostvars[groups['lustre_server'][0]]['lnet_eth0_net_type'] }}"
  squash_group: False # NB if false it IS squashed - to 99. Else use or project name
  squash_user: False  # ditto
  trusted: False
  admin: False
  fileset: False # or subdirectory
  mount_point: /mnt/lustre/
  ssk_flavor:  skn