---
projects:
  proj12:
    owner: 1100 # uid/gid for owner (should start at 1100) and start of shared project user uid/gid range
    member: 1101
    mode: "o=rwx,g=rxwt,o=x"
  proj3:
    owner: 3100
    member: 3101
    mode: "o=rwx,g=rxwt,o=x"
lustre: # can all be overriden on a per-client basis
  release: "2.12.4"
  fs_name: test_fs1
  key_duration: 525600 # duration (s) of lustre key validity
  mgs_addr: "{{ hostvars[groups['lustre_server'][0]]['ansible_host'] }}"
  mgs_lnet: "{{ hostvars[groups['lustre_server'][0]]['lnet_eth0_net_type'] }}"
  squash_gid: 99
  squash_uid: 99
  trusted: False
  admin: False
  deny_unknown: False
  fileset: '' # Use /DIRNAME to mount to a specific subdir and restrict client to that
  mount_point: /mnt/lustre/
  ssk_flavor: 'null' # e.g. skn or 'null' (not null, that's different!) to disable TODO: This can't be changed per-client, so where does it belong?
  idmap: []
users:
  root:
    guid: 0
    groups: []
  nobody:
    guid: 99
    groups: []
