lustre:
  trusted: false
  fileset: "/csd3/proj12"
  idmap:
    - ['uid', "{{ users.root.guid }}", "{{ projects.proj12.users.proj12.guid }}"]
  squash_gid: "{{ projects.proj12.users['proj12'].guid }}"
  squash_uid: "{{ projects.proj12.users['proj12-member'].guid }}"

users:
  becky:
    guid: 1102 # NB deliberately clashes with ldap user alex
    groups: [proj12]
    
  ben:
    guid: 2109
    groups: [proj12]
