lustre:
  trusted: false
  fileset: "/srcp/silver"
  idmap:
    - ['uid', "{{ users.datamanager.guid }}", "{{ projects.silver.owner }}" ]
    - ['gid', "{{ users.datamanager.guid }}", "{{ projects.silver.owner }}" ]
  squash_gid: "{{ projects.silver.member }}"
  squash_uid: "{{ projects.silver.member }}"
users:
  datamanager:
    guid: 2999
    groups: [proj3]
  catrin:
    guid: 1101
    groups: [proj3]
  charlie:
    guid: 3102
    groups: [proj3]