- name: Setup admin client
  hosts: admin_client
  gather_facts: false
  become: true
  tasks:
    - import_role:
        name: client
      vars:
        mount_state: mounted # absent or mounted

    - name: create csd3/srcp directories in lustre fs
      file:
        path: "/mnt/lustre/{{ item }}"
        state: directory
        owner: root
      loop:
        - csd3
        - srcp
      
    - name: create project users/groups (fake LDAP)
      # NB: this is annoying: only needed because ansible's file module (below) needs user/group names, not uid/gids
      import_tasks: project-users.yml

    - name: create project directories in lustre fs
      file:
        path: "/mnt/lustre/{{ item.value.root }}/{{ item.key }}"
        owner: "{{ item.key }}"
        group: "{{ item.key }}"
        mode: "{{ projects[item.key].mode }}"
        state: directory
      loop: "{{ projects | dict2items }}"
