- name: Setup admin client
  hosts: admin_client
  gather_facts: false
  become: true
  roles:
    - role: client
      vars:
        mount_state: mounted # absent or mounted
  tasks:
    - name: create project directories
      file:
        path: "/mnt/lustre/{{ item.value.path }}"
        owner: "{{ item.key }}"
        group: "{{ item.key }}"
        mode: "{{ projects[item.key].mode }}"
        state: directory
      loop: "{{ projects | dict2items }}"