- name: Setup clients
  hosts: lustre_client:!admin_client
  gather_facts: false
  roles:
    - role: common # duplicated here in case this playbook is broken out separately
    - role: client
      become: true
      vars:
        mount_state: mounted # absent or mounted
  