- name: add uuid or uid map
  command: "lctl nodemap_add_idmap --name {{ loop_host | replace('-', '_') }} --idtype {{ item[0] }} --idmap {{ item[1] }}:{{ item[2] }}"
  loop: "{{ hostvars[loop_host].lustre.idmap }}"
  register: add_idmap
  failed_when: "(add_idmap.rc != 0) and ((add_idmap.rc != -1) and ('errno: 17' not in add_idmap.stderr))"
  changed_when: add_idmap.rc == 0
  # existing idmap seems to give "error: invalid ioctl: 000ce044 errno: 17 with rc=-1"
  