---
- name: Check route to server
  hosts: all
  become: True
  gather_facts: false
  tasks:
    - name: test server
      command: "lnetctl ping {{ lustre_server }}"
      changed_when: False

- name: Check route back to net2
  hosts: lustre_server,lnet_router_tcp1_to_tcp2
  become: True
  gather_facts: false
  tasks:
    - name: test client2
      command: "lnetctl ping {{ client_net2 }}"
      changed_when: False
