---
- name: Check route to server(s)
  hosts: all
  become: True
  gather_facts: false
  tasks:
    - command: "lnetctl ping {{ hostvars[item]['ansible_host'] }}@{{ hostvars[item]['lnet_eth0_net_type'] }}"
      changed_when: False
      with_items:
        - "{{ groups['lustre_server'] }}"

- name: Check route from server(s) to clients/routers
  # NB: is this redundant given ping uses both out and back routes? Documents approach at least.
  hosts: lustre_server
  become: True
  gather_facts: false
  tasks:
    - command: "lnetctl ping {{ hostvars[item]['ansible_host'] }}@{{ hostvars[item]['lnet_eth0_net_type'] }}"
      changed_when: False
      with_items:
        - "{{ groups['lustre_client'] | intersect(groups['lustre_router']) }}"

- name: Check clients *cannot* access each other
  hosts: lustre_client
  become: True
  gather_facts: false
  tasks:
    - command: "lnetctl ping {{ hostvars[item]['ansible_host'] }}@{{ hostvars[item]['lnet_eth0_net_type'] }}"
      register: result
      failed_when: 'result.rc == 0'
      changed_when: False
      with_items: "{{ groups['lustre_client'] | difference([inventory_hostname]) }}" # avoids checking self-access