---
- import_playbook: ssh.yml
- import_playbook: entropy.yml
- import_playbook: server.yml
- import_playbook: routers.yml
- import_playbook: projects.yml # needs server. doesn't actually need routers as admin_client in storage network
- import_playbook: clients.yml # needs projects first
- import_playbook: lnet-test.yml
- import_playbook: users.yml
