---
- import_playbook: ssh.yml
- import_playbook: entropy.yml
- import_playbook: install.yml
- import_playbook: lnet.yml
- import_playbook: lnet-test.yml
# next 3 actually configure "projects"
- import_playbook: users.yml
- import_playbook: format.yml
#- import_playbook: nodemap.yml
#- import_playbook: mount.yml
