---
- name: Mount clients
  hosts: lustre_client
  become: True
  vars:
    mount_state: mounted # use mounted or absent
  gather_facts: false
  tasks:

    - name: create project owner groups
      group:
        name: "{{ item }}"
        gid: "{{ projects[item].base }}"
      loop: "{{ projects.keys() }}"

    - name: create project owner users
      user:
        name: "{{ item }}"
        group: "{{ item }}"
        uid: "{{ projects[item].base }}"
        create_home: false # FIXME: seems to have created them in /home
      loop: "{{ projects.keys() }}"

    - name: ensure mount directory exists
      file:
        path: "/mnt/lustre/{{ fs_name }}" #/{{ item }}"
        # TODO: lustre docs suggest /lustre/<fs_name> is "standard". Possibly [/mnt]/lustre/ would be better?
        state: directory

    - name: mount lustre project subdirectory
      # NB: actual subdir set by fileset on nodemap for client
      mount:
        fstype: lustre
        src: "{{ mgsnode }}@{{ lnet_suffix }}:/{{ fs_name }}" #/{{ item }}"
        path: "/mnt/lustre/{{ fs_name }}" #/{{ item }}"
        # submounts are documented in man mount.lustre although not in the docs
        state: "{{ mount_state }}"
        opts: "defaults,_netdev,noauto,x-systemd.automount,x-systemd.requires=lnet.service"
        # opts are systemd defaults from http://wiki.lustre.org/Mounting_a_Lustre_File_System_on_Client_Nodes
  