- name: Configure projects on MGS
  hosts: lustre_server[0] # TODO: MGS group?
  gather_facts: false
  become: true
  tasks:

  - name: create config dir
    file:
      path: /etc/lustre
      owner: root
      state: directory

  - name: load lustre
    command: modprobe lustre
    changed_when: False

  - name: Configure lustre to use ssk for authentication (only) for client to mdt/ost (only)
    command: "lctl conf_param {{ lustre.fs_name }}.srpc.flavor.default.{{ item }}={{ lustre.ssk_flavor }}"
    loop:
      - cli2ost
      - cli2mdt
    # TODO: changed_when e.g. "lctl get_param mgs.*.live.{{ lustre.fs_name }} | grep flavor" => ['test_fs1.srpc.flavor.default.cli2ost=skn', 'test_fs1.srpc.flavor.default.cli2mdt=skn']

  - name: setup ssk shared keys on server
    import_tasks: ssk.yml
    when: "lustre.ssk_flavor != 'null'"

  - name: create nodemap config
    template:
      dest: /etc/lustre/nodemaps.yml
      src: templates/nodemaps.j2

  - name: apply nodemap config
    script: 'tools/lustre-tools/nodemap.py import /etc/lustre/nodemaps.yml'
    register: nodemap_import
    changed_when: "nodemap_import.stdout | trim != ''"
  
  - name: show nodemap changes
    debug:
      msg: "{{ nodemap_import.stdout }}"
    changed_when: false
    
- name: Deploy ssk client keys
  hosts: lustre_client
  gather_facts: false
  become: true
  tasks:
    - block:
      # name: Create lustre config directory # done in projects.yml    

      - name: slurp key from server
        shell:
          cmd: "ssh {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ hostvars['lustre-storage']['ansible_host'] }} -- sudo cat /etc/lustre/{{ inventory_hostname | replace('-', '_') }}.client.key | base64"
        register: client_ssk
        delegate_to: localhost
        become: false
      
      - name: write key to client
        shell:
          cmd: "echo '{{ client_ssk.stdout }}' | base64 -d > /etc/lustre/{{ inventory_hostname | replace('-', '_') }}.client.key"
        # TODO: changed_when - is this even possible??
      
      - name: secure key
        file:
          path: "/etc/lustre/{{ inventory_hostname | replace('-', '_') }}.client.key"
          mode: 0600
      
      when: "lustre.ssk_flavor != 'null'"

# TODO: ensure group upcall is default:
# sudo lctl set_param mdt.test_fs1-MDT0000.identity_upcall=/usr/sbin/l_getidentity