- name: create project owner groups
  group:
    name: "{{ item }}"
    gid: "{{ projects[item].owner_guid }}"
  loop: "{{ projects.keys() }}"

- name: create project owner users
  user:
    name: "{{ item }}"
    group: "{{ item }}"
    uid: "{{ projects[item].owner_guid }}"
    create_home: false # FIXME: seems to have created them in /home
  loop: "{{ projects.keys() }}"

- name: create project member groups
  group:
    name: "{{ item }}-member"
    gid: "{{ projects[item].member_guid }}"
  loop: "{{ projects.keys() }}"

- name: create project member users
  user:
    name: "{{ item }}-member"
    group: "{{ item }}"
    uid: "{{ projects[item].member_guid }}"
    create_home: false # FIXME: seems to have created them in /home
  loop: "{{ projects.keys() }}"
