---
- name: Setup projects
  hosts: lustre_server[0] # TODO: MGS group?
  become: true
  gather_facts: false
  tasks:

  - name: load lustre
    command: modprobe lustre
    changed_when: False

  - name: create admin nodemap
    command: "lctl nodemap_add admin"
    register: admin_nodemap_add
    failed_when: admin_nodemap_add.rc != 0 and ('existing nodemap name' not in admin_nodemap_add.stderr)
    changed_when: admin_nodemap_add.rc == 0

  - name: add MGS to admin nodemap
    command: "lctl nodemap_add_range --name admin --range {{ mgsnode }}@{{ lnet_suffix }}"
    register: admin_nodemap_add_range
    failed_when: "admin_nodemap_add_range.rc != 0 and ('errno: 12' not in admin_nodemap_add_range.stderr)"
    changed_when: admin_nodemap_add_range.rc == 0

  - name: make admin nodemap trusted
    command: "lctl nodemap_modify --name admin --property trusted --value 1"
    # TODO: changed_when
    
  - name: make admin nodemap admin
    command: "lctl nodemap_modify --name admin --property admin --value 1"
    # TODO: changed_when

  - name: activate nodemaps
    shell: "lctl get_param nodemap.* ; lctl nodemap_activate 1; lctl get_param nodemap.* "
    register: nodemap_activate
    failed_when: "'nodemap.active=1' not in nodemap_activate.stdout_lines" # for some reason get_param's rc is 5
    changed_when: "nodemap_activate.stdout_lines == ['nodemap.active=0','nodemap.active=1']"
    # TODO: this is dead hacky!

  - name: create lustre filesystem mountpoint on MGS
    file:
      path: "/mnt/lustre/{{ fs_name }}"
      state: directory
  
  - name: mount lustre filesystem on MGS
    mount:
      fstype: lustre
      src: "{{ mgsnode }}@{{ lnet_suffix }}:/{{ fs_name }}"
      path: "/mnt/lustre/{{ fs_name }}"
      state: mounted
      opts: "defaults,_netdev,noauto,x-systemd.automount,x-systemd.requires=lnet.service"
      # opts are systemd defaults from http://wiki.lustre.org/Mounting_a_Lustre_File_System_on_Client_Nodes

  - name: add client nodemaps
    command: "lctl nodemap_add {{ item | replace('-', '_') }}" # TODO: undocumented restrictions in nodeset names: so far know "-" and "." aren't allowed.
    loop: "{{ groups['lustre_client'] }}"
    register: nodemap_add
    failed_when: nodemap_add.rc != 0 and ('existing nodemap name' not in nodemap_add.stderr)
    changed_when: nodemap_add.rc == 0

  - name: add clients to client nodemaps
    command: "lctl nodemap_add_range --name {{ item | replace('-', '_') }} --range {{ hostvars[item]['ansible_host'] }}@{{ hostvars[item]['lnet_eth0_net_type'] }}" # client NID
    register: nodemap_add_range
    loop: "{{ groups['lustre_client'] }}"
    failed_when: "nodemap_add_range.rc != 0 and ('errno: 12' not in nodemap_add_range.stderr)"
    changed_when: nodemap_add_range.rc == 0

  - name: configure client nodemaps with filesets
    command: "lctl nodemap_set_fileset --name {{ item | replace('-', '_') }} --fileset '/{{ hostvars[item].mount.name }}'" # NB can't check this is a valid path!
    loop: "{{ groups['lustre_client'] }}"
    # TODO: need to make permanent too - see docs
    # TODO: check using lctl get_param nodemap.proj3.ranges?

  - name: configure client nodemaps to squash groups
    # TODO: has to be done with the nodemap inactive?
    command: "lctl nodemap_modify --name {{ item | replace('-', '_') }} --property squash_gid --value {{ projects[hostvars[item].mount.name].base }}"
    loop: "{{ groups['lustre_client'] }}"
    when: hostvars[item].mount.squashed

  - name: configure client nodemaps to squash users
    # TODO: has to be done with the nodemap inactive?
    # clientname ->     -> projectname
    command: "lctl nodemap_modify --name {{ item | replace('-', '_') }} --property squash_uid --value {{ projects[hostvars[item].mount.name].base }}"
    loop: "{{ groups['lustre_client'] }}"
    when: hostvars[item].mount.squashed
    # note can run this multiple times with no (direct) way to tell if it's changed
  
  - name: configure client nodemaps not to translate uid/gids
    command: "lctl nodemap_modify --name {{ item | replace('-', '_') }} --property trusted --value 1"
    loop: "{{ groups['lustre_client'] }}"
    when: hostvars[item].mount.trusted

  # TODO: setup ssk

  - name: create project owner groups
    group:
      name: "{{ item }}"
      gid: "{{ projects[item].base }}"
    loop: "{{ projects.keys() }}"

  - name: create project owner users
    user:
      name: "{{ item }}"
      group: "{{ item }}"
      uid: "{{ projects[item].base }}"
      create_home: false # FIXME: seems to have created them in /home
    loop: "{{ projects.keys() }}"

  - name: create project directories with setgid bit set
    file:
      path: "/mnt/lustre/{{ fs_name }}/{{ item }}"
      owner: "{{ item }}"
      group: "{{ item }}"
      mode: "2770"
      state: directory
    loop: "{{ projects.keys() }}"
