- name: setup project directories
  hosts: admin_client
  become: true
  vars:
    mount_state: mounted
  tasks:
    - import_tasks: configure-client.yml
    - name: create project directories
      file:
        path: "/mnt/lustre/{{ item.key }}"
        owner: "{{ item.key }}"
        group: "{{ item.key }}"
        state: directory
      loop: "{{ projects | dict2items }}"
