---

- name: create test groups
  group:
    name: "{{ item }}"
    gid: "{{ users[item].guid }}"
    state: present
  loop: "{{ users.keys() }}"
  
- name: create test users
  user:
    name: "{{ item }}"
    uid: "{{ users[item].guid }}"
    group: "{{ item }}"
    groups: "{{ users[item].groups }}"
    state: present
    remove: "yes"
  loop: "{{ users.keys() }}"
