---
- name: Create project-owner users # TODO: check user-private groups are ok?
  hosts: lustre_server,lustre_client
  become: true
  gather_facts: false
  tasks:

    - name: create project groups
      group:
        name: "{{ item.name }}"
        gid: "{{ item.base }}"
      loop: "{{ projects }}"

    - name: create project users
      user:
        name: "{{ item.name }}"
        group: "{{ item.name }}"
        uid: "{{ item.base }}"
        create_home: false # FIXME: seems to have created them in /home
      loop: "{{ projects }}"

    - name: create shared client groups
      group:
        name: "{{ item.1.keys()[0] }}"
        gid: "{{ item.1.values()[0] }}"
      when: (mounts is defined and item.0.name == mounts[0].name) or ('lustre_server' in group_names) # i.e. servers, and 
      loop: "{{ projects | subelements('shared_users') }}"
      
      # TODO: only on clients mounting this project!

    - name: create shared client users
      user:
        name: "{{ item.1.keys()[0] }}"
        uid: "{{ item.1.values()[0] }}"
        groups:
          - "{{ item.0.name }}"
      when: (mounts is defined and item.0.name == mounts[0].name) or ('lustre_server' in group_names)
      loop: "{{ projects | subelements('shared_users') }}"
      # TODO: only on clients mounting this project!


- name: Create client-only users
  hosts: lustre_client
  become: true
  gather_facts: false
  tasks:

    - name: create user groups
      group:
        name: "{{ item.keys()[0] }}"
        gid: "{{ item.values()[0] }}"
      loop: "{{ local_users }}"
      when: local_users is defined

    - name: create users
      user:
        name: "{{ item.keys()[0] }}"
        group: "{{ item.keys()[0] }}"
        uid: "{{ item.values()[0] }}"
        create_home: true
      loop: "{{ local_users }}"
      when: local_users is defined
