- name: Fake LDAP for server
  hosts: lustre-storage[0]
  gather_facts: false
  become: true
  tasks:
    - name: create project owner users/groups
      import_tasks: project-users.yml

    - name: create project user user/groups
      import_tasks: test-users.yml
      vars:
        users: "{{ hostvars['lustre-client1']['users'] }}"

- name: Setup client users
  hosts: lustre_client:!admin_client
  gather_facts: false
  become: true
  tasks:
    - name: create project owner users/groups
      import_tasks: project-users.yml

    - name: create project user user/groups
      import_tasks: test-users.yml
      
    