---
- name: Create users # TODO: check user-private groups are ok?
  hosts: lustre_server,lustre_client
  become: true
  gather_facts: false
  tasks:

    - name: create project groups
      group:
        name: "{{ item.key }}"
        gid: "{{ item.value }}"
      loop: "{{ projects | dict2items }}"

    - name: create project users
      user:
        name: "{{ item.key }}"
        group: "{{ item.key }}"
        uid: "{{ item.value }}"
        create_home: false # FIXME: seems to have created them in /home
      loop: "{{ projects | dict2items }}"

    - name: create project client groups
      group:
        name: "{{ item.keys()[0] }}"
        gid: "{{ item.values()[0] }}"
      loop: "{{ users }}"

    - name: create project client users
      user:
        name: "{{ item.keys()[0] }}"
        group: "{{ item.keys()[0] }}"
        uid: "{{ item.values()[0] }}"
      loop: "{{ users }}"        
