---
- name: Create test users
  hosts: lustre_client:!admin_client
  become: true
  gather_facts: false
  tasks:

    - name: create groups
      group:
        name: "{{ item }}"
        gid: "{{ users[item].guid }}"
        state: present
      loop: "{{ users.keys() }}"
    
    - name: create users
      user:
        name: "{{ item }}"
        uid: "{{ users[item].guid }}"
        group: "{{ item }}"
        groups: "{{ users[item].groups }}"
        state: present
        remove: "yes"
      loop: "{{ users.keys() }}"
