---
- name: Create users
  hosts: lustre_server,lustre_client
  become: true
  gather_facts: false
  tasks:

    - name: create groups
      group:
        name: "{{ item }}"
        gid: "{{ users[item].guid }}"
      loop: "{{ users.keys() }}"
    
    - name: create users
      user:
        name: "{{ item }}"
        uid: "{{ users[item].guid }}"
        group: "{{ item }}"
        groups: "{{ users[item].groups }}"
      loop: "{{ users.keys() }}"
