mount:
  name: proj12
  squashed: true
  trusted: false
users: # NB neither of these exist on the server
  becky:
    guid: 1101 # NB deliberately clashes with a client1 user
    groups: [proj12] # empty as user not present on server
  ben:
    guid: 2109
    groups: [proj12]
